FROM node:alpine

WORKDIR /react/app

COPY package.json .
RUN npm install

COPY . .
# instead of copying docker can refer to files in local
# Concept of Docker Volume just like port mapping

CMD ["npm","start"]
# > docker build -f Dockerfile.dev -t <docker id/projectname:version>
# > docker run -it -p 3000:3000 CONTAINER_ID -v <local files/dir> : <remote files/dir>
# Here we can use node_modules of local or inside container, so use -v parameter

# To test > npm test one can run below
# > docker exec -it <container id> npm test